[package]
name = "banyan-ipfs-camp-2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
banyan = "0.17.1"
banyan-utils = "0.10.1"
